### ISSUE TITLE
Registration Worker: Guest Lookup

### ISSUE THREAD

**Issue by seanbseanb** [CON-In-A-Box/CIAB-Signin#253] opened 2019-04-09 12:58 UTC
Registration Workers should be able to look up guest registrations by last name, email address , or badge number.

**Comment by seanbseanb** [comment] 2019-04-09 13:07
I believe last name/first name is already closed, pending review.

**Comment by AricStewart** [comment] 2019-04-09 13:11
Any of the lookup bars should respond to full names (Real or preferred) , email and badge number

https://ciab.anergyst.org/index.php?Function=registration

If you need to be able to look someone up by JUST last name I can add that facility.

**Comment by AricStewart** [comment] 2019-04-09 17:48
Please test the functionality.

**Comment by AricStewart** [comment] 2019-04-10 22:00
Check it out again please.. updated:
https://ciab.anergyst.org/index.php?Function=registration&memberId=1231

**Comment by mshappe** [comment] 2019-08-11 02:02
What is the current status of this issue?

**Comment by AricStewart** [comment] 2019-08-12 16:33
I believe this is complete and just was waiting on official testing/closing.

**Comment by AricStewart** [comment] 2019-09-28 01:35
I am going to poke this one last time and then just close it as fixed and inactive.

**Comment by mshappe** [comment] 2019-10-01 01:01
This appears to work as intended.

**Closed by mshappe** 2019-10-01 01:01 UTC
